project:
  type: website
  output-dir: docs

website:
  title: "Derek H. Ogle"
  favicon: zresources/img/DerekOgle1.jpg
  site-url: https://derekogle.com/
  repo-url: https://github.com/droglenc/droglenc.github.io
  navbar:
    title: Derek H. Ogle
    background: "#25383C"
    foreground: "#E5E4E2"
    pinned: true
    left:
      - text: "Professional"
        href: professional/index.qmd
      - text: "Personal"
        href: personal/index.qmd
      - text: "Portfolio"
        href: portfolio/index.qmd
  sidebar:
    - id: professional
      title: "Professional"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: "Professional"
          href: professional/index.qmd
        - text: "Publications"
          href: professional/publications.qmd
        - text: "Software"
          href: professional/software.qmd
    - id: personal
      title: "Personal"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: "Personal"
          href: personal/index.qmd
        - section: "Hiking/Walking"
          contents:
            - text: "Iron River Area"
              href: personal/Hiking/Iron River Area.qmd
            - text: "Superstition Wilderness"
              href: personal/Hiking/Superstition Wilderness.qmd
            - text: "Iowa"
              href: personal/Hiking/Iowa.qmd
            - text: "Other Notable"
              href: personal/Hiking/Other Notable.qmd
        - text: "Shelties"
          href: personal/shelties.qmd
        - text: "Fishing"
          href: personal/fishing.qmd
        - text: "Live Music"
          href: personal/music.qmd
        - text: "Oulu Property"
          href: personal/oulu.qmd
        - text: "TV Appearances"
          href: personal/tv.qmd
  page-footer:
    background: "#25383C"
    foreground: "#E5E4E2"
    left: "Copyright 2023, Derek H. Ogle"
    center:
      - text: fishR
        href: https://fishr-core-team.github.io/fishR/
        aria-label: fishR webpage
      - text: IFAR
        href: https://derekogle.com/IFAR/
        aria-label: IFAR book
    right:
      - icon: github
        href: https://github.com/droglenc/droglenc.github.io
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/DerekOgle51
        aria-label: Twitter
  search: false
  comments: false
  open-graph: true
format:
  html:
    theme: [litera, zhelpers/custom.scss]
    css: zhelpers/styles.css
    mainfont: sans-serif
    backgroundcolor: "#FEFCFF"
    linkcolor: "#571B7E"
    link-external-icon: false
    link-external-newwindow: true
    smooth-scroll: true
    title-block-banner: false
    toc: true
    email-obfuscation: references
highlight-style: github
date-format: medium
execute:
  freeze: auto
