---
title: "Pulpit Rock - Decorah, IA"
---

On 19-Jan-2023 [Cash](../shelties.html#cash) and I stopped in Decorah to walk the short but beautiful Pulpit Rock Trail. Details are below.

```{r setup, include=FALSE}
#| label: setup
#| include: false

# Make vector of colors for Iron River Area
clrs <- c("Highway"="#CC0000","Paved"="#336666",
          "Gravel"="#CC6600","Offroad"="#CC9900",
          "Trail"="#999933", "ATV"="#663300")

# Read in CSV file will all track info needed for the map
project <- "Iowa"
trkdat <- read.csv(paste0("c:/aaaPersonal/MAPPING/Data/",project,"_trkdat.csv"))
trkinfo <- read.csv(paste0("c:/aaaPersonal/MAPPING/Data/",project,"_trkinfo.csv"))

# Make the walk
walkIDs <- c("PLPT01","PLPT02","PLPT03","PLPT07","PLPT08","PLPT08","PLPT06","PLPT03","PLPT04")
awalk <- gpxhelpers::walkMaker(trkdat,trkinfo,walkIDs,findOrder=FALSE)

# Get photos
pix <- readxl::read_excel("c:/aaaPersonal/MAPPING/Data/Trail Mapping Info.xlsx",sheet="Photos")
walkPix <- gpxhelpers::walkGetPhotos(pix,walkIDs,"https://github.com/droglenc/MAPPING/raw/main/Images")
npix <- nrow(walkPix)
```

## Walk-Specific Map
```{r}
#| label: walkMap
#| echo: false
gpxhelpers::walkMap(awalk,clrs,verbose=FALSE)
```

:::{.callout-note appearance="simple"}
## Take Note
- Click on a segment to get specific information.
- Numeric labels correspond to the same labels in the elevation profile and summary information below.
:::

## Elevation Profile
```{r}
#| label: walkElevation
#| echo: false
gpxhelpers::walkElevation(awalk)
```

## Summary Information
```{r}
#| label: walkSummary
#| echo: false
gpxhelpers::walkSummary(awalk)
```

## Images
```{r}
#| echo: false
#| results: asis
gpxhelpers::makeCarousel(id="Walk",path="",
                         imgs=walkPix$Photo,caps=walkPix$Caption,
                         width=75,captions=TRUE,controls=TRUE,indicators=FALSE)
```
